#pragma once

// PUBG MOBILE (2.8.0) SDKGenerated by @aynb6 || 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @AYMOD6 
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function SettingConfig.SettingConfig_C.ConditionSetFireGyroData
struct USettingConfig_C_ConditionSetFireGyroData_Params
{
};

// Function SettingConfig.SettingConfig_C.Init
struct USettingConfig_C_Init_Params
{
};

}

