#pragma once

// PUBG MOBILE (2.8.0) SDKGenerated by @aynb6 || 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @AYMOD6 
namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// Enum QuantumDevKit.EQuantumFirebaseRemoteConfigStatus
enum class EQuantumFirebaseRemoteConfigStatus : uint8_t
{
	EQuantumFirebaseRemoteConfigStatus__kUnfetched = 0,
	EQuantumFirebaseRemoteConfigStatus__kFetchedSuccessfully = 1,
	EQuantumFirebaseRemoteConfigStatus__kFetchedFailed = 2,
	EQuantumFirebaseRemoteConfigStatus__EQuantumFirebaseRemoteConfigStatus_MAX = 3
};



}

