#pragma once

// PUBG MOBILE (2.8.0) SDKGenerated by @aynb6 || 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @AYMOD6 
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Login_UIBP.Login_UIBP_C.SetRenderTransformWheniPhone
struct ULogin_UIBP_C_SetRenderTransformWheniPhone_Params
{
};

// Function Login_UIBP.Login_UIBP_C.Construct
struct ULogin_UIBP_C_Construct_Params
{
};

// Function Login_UIBP.Login_UIBP_C.ExecuteUbergraph_Login_UIBP
struct ULogin_UIBP_C_ExecuteUbergraph_Login_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

