#pragma once

// PUBG MOBILE (2.8.0) SDKGenerated by @aynb6 || 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @AYMOD6 
namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// UserDefinedEnum RankIntegralType.RankIntegralType
enum class ERankIntegralType : uint8_t
{
	RankIntegralType__NewEnumerator2 = 0,
	RankIntegralType__NewEnumerator3 = 1,
	RankIntegralType__NewEnumerator1 = 2,
	RankIntegralType__NewEnumerator0 = 3,
	RankIntegralType__NewEnumerator5 = 4,
	RankIntegralType__NewEnumerator6 = 5,
	RankIntegralType__NewEnumerator7 = 6,
	RankIntegralType__RankIntegralType_MAX = 7
};



}

